title: Dr. Syed Faizan, MBBS
logo: /assets/img/headshot_circle.png
description: I am currently a graduate student in the Master's of Professional Studies program in Data Analytics and Applied Machine Learning at Northeastern University. 
A physician bringing my medical domain expertise to the world of Machine Learning and Deep Learning.
show_downloads: true
theme: jekyll-theme-architect
